### ISSUE TITLE
Supporting web?

### ISSUE THREAD

**Issue by manuxstack** [SchabanBo/qlevar_local_manager#1]
Hi!

This is a pretty cool tool, but it's only working for windows. Do you have plans to support web versions?
In my case I'm using Mac, so it's a little bit difficult to use It.

Thanks!

**Comment by SchabanBo** [comment]
Hi @rfmanuj,
I'm working currently on the drag and drop functionality. Web support is my next step 👍

**Comment by SchabanBo** [comment]
@rfmanuj [Website](https://local-manager.netlify.app)
