### ISSUE TITLE
No way to delete or modify a column (language) [feature request]

### ISSUE THREAD

**Issue by Xardas365** [SchabanBo/qlevar_local_manager#2]
There is no way to delete or modify a column (language) in an web application. Of course we can edit exported project json and import, but is not comfortable.

**Comment by SchabanBo** [comment]
@Xardas365 Good point.
I will add this.

**Comment by SchabanBo** [comment]
I am sorry, I finished this two months ago but forget to make a release for it. I made one today V1.3.0
